"""Entry point for the final Component 2 repository.

The exact paper/dissertation results are generated by the consolidated v8
notebook because it contains the full staged protocol and frozen selection
provenance.
"""
from pathlib import Path
from config import FUSION_WEIGHT

HERE = Path(__file__).resolve().parent
FINAL_NOTEBOOK = HERE / "notebooks" / "component2_consolidated_v8.ipynb"
RESULTS_FILE = HERE / "results" / "results_v8.json"

def main():
    print("Component 2 — consolidated GLOBEM v8")
    print(f"Notebook : {FINAL_NOTEBOOK}")
    print(f"Results  : {RESULTS_FILE}")
    print("Held-out GATv2 AUROC : 0.5205 [0.485, 0.560]")
    print("Permutation p-value : 0.255")
    print(f"Fusion weight       : {FUSION_WEIGHT:.1f}")
    print()
    print("Use the consolidated notebook to reproduce the final reported results.")

if __name__ == "__main__":
    main()
