import os
import warnings
from pathlib import Path
from dotenv import load_dotenv

# Project Root
PROJECT_ROOT = Path(__file__).parents[1].resolve()

# Load environment variables from .env file
load_dotenv(PROJECT_ROOT / ".env")

# Raw Data Paths
MIMIC_IV_DATASET_PATH = os.getenv("MIMIC_IV_DATASET_PATH")
MIMIC_IV_NOTE_DATASET_PATH = os.getenv("MIMIC_IV_NOTE_DATASET_PATH")

# Processed Data Paths
MIMIC_PROCESSED_BASE_DIR = os.getenv(
    "MIMIC_PROCESSED_BASE_DIR", str(PROJECT_ROOT / "data" / "processed")
)
MIMIC_PROCESSED_PKL_DIR = os.getenv(
    "MIMIC_PROCESSED_PKL_DIR", str(PROJECT_ROOT / "data" / "processed" / "pkl")
)
MIMIC_ANALYSIS_PATH = os.getenv(
    "MIMIC_ANALYSIS_PATH", str(PROJECT_ROOT / "data" / "processed" / "mimic_analysis")
)

# New Split Data Paths generated by extract_data.py
MIMIC_TRAIN_BALANCED_PATH = os.getenv(
    "MIMIC_TRAIN_BALANCED_PATH",
    str(Path(MIMIC_PROCESSED_BASE_DIR) / "mimic_anxiety_train_balanced.csv"),
)
MIMIC_TRAIN_HIGH_CONF_PATH = os.getenv(
    "MIMIC_TRAIN_HIGH_CONF_PATH",
    str(Path(MIMIC_PROCESSED_BASE_DIR) / "mimic_anxiety_train_high_conf.csv"),
)
MIMIC_VAL_PATH = os.getenv(
    "MIMIC_VAL_PATH",
    str(Path(MIMIC_PROCESSED_BASE_DIR) / "mimic_anxiety_val_real_world.csv"),
)
MIMIC_TEST_PATH = os.getenv(
    "MIMIC_TEST_PATH",
    str(Path(MIMIC_PROCESSED_BASE_DIR) / "mimic_anxiety_test_real_world.csv"),
)
MIMIC_TEST_HIGH_CONF_PATH = os.getenv(
    "MIMIC_TEST_HIGH_CONF_PATH",
    str(Path(MIMIC_PROCESSED_BASE_DIR) / "mimic_anxiety_test_high_conf.csv"),
)

# Validation
if not MIMIC_IV_DATASET_PATH:
    warnings.warn("MIMIC_IV_DATASET_PATH is not set in the environment variables.")
if not MIMIC_IV_NOTE_DATASET_PATH:
    warnings.warn("MIMIC_IV_NOTE_DATASET_PATH is not set in the environment variables.")
