name: anxiety_mobile_app
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  #################################
  # New Dependencies can be added here
  ###############################

  google_fonts: ^6.1.0

  # Networking / backend
  http: ^1.2.0
  supabase_flutter: ^2.16.0
  qr_flutter: ^4.1.0

  # Data Storage
  shared_preferences: ^2.2.0
  intl: ^0.18.1
  connectivity_plus: ^4.0.1

  # Sensors & Data
  geolocator: ^13.0.0 # Location
  usage_stats: ^1.2.0 # App Usage
  call_log: ^6.0.1 # Call History
  # telephony: ^0.2.0         # SMS
  flutter_sms_inbox: ^1.0.3
  sensors_plus: ^5.0.0 # Movement (Accelerometer)
  battery_plus: ^6.0.0 # Battery status

  # Background Execution
  flutter_background_service: ^5.0.0
  flutter_local_notifications: ^17.0.0

  # Permissions
  permission_handler: ^11.3.0

  screen_state: ^4.1.1
  device_info_plus: ^9.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  fl_chart: ^1.2.0
  app_settings: ^8.0.3
  image_picker: ^1.1.2
  flutter_blue_plus: ^1.31.0

  #################################

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21


flutter:
  uses-material-design: true
  assets:
    - assets/meditation_hero.jpg
    - assets/welcome_illustration.png

